routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\ResetPasswordController;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\financial_yearController;
use App\Http\Controllers\departmentController;
use App\Http\Controllers\statusController;
use App\Http\Controllers\organizationController;
use App\Http\Controllers\document_numberingController;
use App\Http\Controllers\file_masterController;
use App\Http\Controllers\QrCodeController;
use App\Http\Controllers\Department_DetailsController;
use App\Http\Controllers\InwardController;
use App\Http\Controllers\InwardformController;
use App\Http\Controllers\ForwardController;
use App\Http\Controllers\ForwardformController;
use App\Http\Controllers\mis_user_wiseController;
use App\Http\Controllers\Error_PageController;
use App\Http\Controllers\In_TransitController;
use App\Http\Controllers\CloseController;
use App\Http\Controllers\CloseformController;
use App\Http\Controllers\File_TypeController;
use App\Http\Controllers\MISController;
use App\Http\Controllers\file_statusController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

/* -------------------------------Authenticate starting here -------------------------------------- */
// User Register
Route::get('/register', [RegisterController::class, 'register'])->name('register');
Route::post('/register/store', [RegisterController::class, 'store'])->name('register.store');

// User Login
Route::get('/login', [LoginController::class, 'login'])->name('login');
Route::post('/login/store', [LoginController::class, 'authenticate'])->name('login.store');

// Logout
Route::get('/logout', [LoginController::class, 'logout'])->name('dept_logout');

// Forgot Password Password
Route::get('/forget-password', [ForgotPasswordController::class, 'getEmail'])->name('forget-password');
Route::post('/forget-password/store', [ForgotPasswordController::class, 'postEmail'])->name('forget-password.store');

// Password reset routes...
Route::get('/reset-password/{token}', [ResetPasswordController::class, 'getPassword'])->where('token','[0-9a-zA-Z]+')->name('reset-password');
Route::post('/reset-password', [ResetPasswordController::class, 'updatePassword'])->name('reset-password.update');

/* -------------------------------Authenticate ending here ---------------------------------------- */

Route::group(['middleware' => ['auth', 'preventBackHistoryMiddleware']], function() {

    // Dashboard
    Route::get('/index', [HomeController::class, 'index'])->name('admin_dashboard');

    // Upload File Directory
    Route::get('/d', [HomeController::class, 'd'])->name('upload_file_d');

    /* ------------User Online Status ------------ */
    Route::get('/check', [UserController::class, 'userOnlineStatus'])->name('UserOnlineStatus');

    /* ---------------------------------------Setup start here.----------------------------------- */
    Route::resource('/users', RegisterController::class);
    Route::resource('/financial_year', financial_yearController::class);
    Route::resource('/department', departmentController::class);
    Route::resource('/status', statusController::class);
    Route::resource('/organization', organizationController::class);
    Route::resource('/document_numbering', document_numberingController::class);


    /* --------------------------------------- File Master ----------------------------------- */
    Route::resource('/file_master', file_masterController::class);
    Route::get('/file_master_log_history/{id}', [file_masterController::class, 'File_Master_Log_History'])->name('File_Master_Log_History');

    Route::get('/generate-qrcode/{id}', [QrCodeController::class, 'index'])->name('generate-qrcode');
    Route::get('/Department_Details/{id}', [Department_DetailsController::class, 'Department_Details'])->name('Department_Details');

    Route::get('/Inward', [InwardController::class, 'Inward'])->name('Inward');
    Route::get('/Inwardsearch', [InwardController::class, 'search'])->name('Inwardsearch');
    Route::resource('/Inwardform', InwardformController::class);

    Route::get('/Forward', [ForwardController::class, 'Forward'])->name('Forward');
    Route::get('/Forwardsearch', [ForwardController::class, 'forwardsearch'])->name('Forwardsearch');
    Route::resource('/Forwardform', ForwardformController::class);
    Route::post('api/department-user', [ForwardController::class, 'DepartmentUser']);
    Route::post('department-table-no', [ForwardController::class, 'DepartmentUserTableNumber']);

    Route::resource('/in_transit', In_TransitController::class);

    Route::get('/Close', [CloseController::class, 'Close'])->name('Close');
    Route::get('/Closefilesearch', [CloseController::class, 'Closedsearch'])->name('Closefilesearch');
    Route::resource('/close_result', CloseformController::class);

    /* ---------------------------------------Master File start here.----------------------------------- */
    Route::resource('/file_type', File_TypeController::class);

    /* --------------------------------------- Report ----------------------------------- */
    Route::get('/MIS', [MISController::class, 'MIS'])->name('MIS');
    Route::get('/mis_department_user_wise/{id}', [MISController::class, 'mis_department_user_wise'])->name('mis_department_user_wise');
    Route::get('/mis_user_wise', [mis_user_wiseController::class, 'mis_user_wise'])->name('mis_user_wise');
    Route::get('/file_status', [file_statusController::class, 'file_status'])->name('file_status');
    Route::get('/check_file_history', [file_statusController::class, 'check_file_history'])->name('check_file_history');
    Route::post('/check_file_history_search', [file_statusController::class, 'check_file_history_search'])->name('check_file_history_search');

    // ----------------------------- search user management ------------------------------//
    Route::post('search/user/list', [mis_user_wiseController::class, 'searchUser'])->name('search/user/list');

});

/* ---------------------------------------Error Pages start here.---------------------------------- */
Route::get('/400_Error', [Error_PageController::class, '400_Error'])->name('400_Error');
Route::get('/403_Error', [Error_PageController::class, '403_Error'])->name('403_Error');
Route::get('/404_Error', [Error_PageController::class, '404_Error'])->name('404_Error');
Route::get('/500_Error', [Error_PageController::class, '500_Error'])->name('500_Error');
Route::get('/503_Error', [Error_PageController::class, '503_Error'])->name('503_Error');

resources/views/Document Numbering/create.blade.php
@extends('adminlayouts.master')
@section('content')

    <style>
        .err {
            color: red;
        }

    </style>

    <div class="page-header">
        <div class="title">
            <h4 class="text-primary">Add Document Numbering </h4>
        </div>
    </div>

    <form method="post" action="{{ url('document_numbering') }}" class="form-horizontal" enctype="multipart/form-data">
        {{ csrf_field() }}

        <div class="pd-20 card-box mb-30 ">
            
            <div class="form-group row mt-3">
                <label class="col-sm-2">Name :<span style="color:red;"> *</span></label>
                <div class="col-sm-4 col-md-4">
                    <input type="text" name="name" id="name" class="form-control  @error('name') is-invalid @enderror"
                        value="" placeholder="Enter Name.">
                    @if ($errors->has('name'))
                        <span class="err">
                            <strong>{{ $errors->first('name') }}.</strong>
                        </span>
                    @endif
                </div>

                <label class="col-sm-2 pt-2">Company Name :<span style="color:red;"> *</span></label>
                <div class="col-sm-4 col-md-4">
                    <select class="custom-select2 form-control @error('company') is-invalid @enderror" name="company"
                        id="company" style="width: 100%; height: 38px;">
                        <option value="">Please Select Company </option>
                        <optgroup label="">
                            @foreach($organization as $key => $comps)
                               <option value="{{ $key }}">{{ $comps }}</option>
                            @endforeach
                        </optgroup>
                    </select>
                    @if ($errors->has('company'))
                        <span class="err">
                            <strong>{{ $errors->first('company') }}.</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group row mt-3">
                <label class="col-sm-2 pt-2">Document Type :<span style="color:red;"> *</span></label>
                <div class="col-sm-4 col-md-4">
                    <select class="custom-select2 form-control @error('document_type') is-invalid @enderror" name="document_type"
                        id="document_type" style="width: 100%; height: 38px;">
                        <option value="">Please Select Document Type </option>
                        <optgroup label="">
                            <option value="File">File</option>
                            <option value="QR-Code">QR-Code</option>
                        </optgroup>
                    </select>
                    @if ($errors->has('document_type'))
                        <span class="err">
                            <strong>{{ $errors->first('document_type') }}.</strong>
                        </span>
                    @endif
                </div>
                
                <label class="col-sm-2 pt-2">Financial Year :<span style="color:red;"> *</span></label>
                <div class="col-sm-4 col-md-4">
                    <select class="custom-select2 form-control @error('financial_year') is-invalid @enderror" name="financial_year"
                        id="financial_year" style="width: 100%; height: 38px;">
                        <option value="">Please Select Financial Year </option>
                        <optgroup label="">
                            @foreach($financial_year as $key => $comps)
                               <option value="{{ $key }}">{{ $comps }}</option>
                            @endforeach
                        </optgroup>
                    </select>
                    @if ($errors->has('financial_year'))
                        <span class="err">
                            <strong>{{ $errors->first('financial_year') }}.</strong>
                        </span>
                    @endif
                </div>
            </div>
            
            <div class="form-group row mt-3">
                <label class="col-sm-2">Prefix :</label>
                <div class="col-sm-4 col-md-4">
                    <input type="text" name="prefix" id="prefix"
                        class="form-control  @error('prefix') is-invalid @enderror" value=""
                        placeholder="Enter Prefix.">
                    @if ($errors->has('prefix'))
                        <span class="err">
                            <strong>{{ $errors->first('prefix') }}.</strong>
                        </span>
                    @endif
                </div>

                <label class="col-sm-2">Suffix :</label>
                <div class="col-sm-4 col-md-4">
                    <input type="text" name="suffix" id="suffix" class="form-control  @error('suffix') is-invalid @enderror"
                        value="" placeholder="Enter Suffix.">
                    @if ($errors->has('suffix'))
                        <span class="err">
                            <strong>{{ $errors->first('suffix') }}.</strong>
                        </span>
                    @endif
                </div>
            </div>
            
            <div class="form-group row mt-3">
                <label class="col-sm-2">Start Doc. No. :</label>
                <div class="col-sm-4 col-md-4">
                    <input type="text" name="Start_Doc_No" id="Start_Doc_No" class="form-control  @error('Start_Doc_No') is-invalid @enderror" value="" placeholder="Enter Starting Document Number.">
                    @if ($errors->has('Start_Doc_No'))
                        <span class="err">
                            <strong>{{ $errors->first('Start_Doc_No') }}.</strong>
                        </span>
                    @endif
                </div>

                <label class="col-sm-2">End Doc. No. :</label>
                <div class="col-sm-4 col-md-4">
                    <input type="text" name="End_Doc_No" id="End_Doc_No" class="form-control  @error('End_Doc_No') is-invalid @enderror" value="" placeholder="Enter Ending Document Number.">
                    @if ($errors->has('End_Doc_No'))
                        <span class="err">
                            <strong>{{ $errors->first('End_Doc_No') }}.</strong>
                        </span>
                    @endif
                </div>
            </div>
            
            <div class="form-group row mt-3">
                <label class="col-sm-2 pt-2">Document Numbering Status :<span style="color:red;"> *</span></label>
                <div class="col-sm-4 col-md-4">
                    <select class="custom-select2 form-control @error('status') is-invalid @enderror" name="status"
                        id="status" style="width: 100%; height: 38px;">
                        <option value="">Please Select Document Status </option>
                        <optgroup label="">
                            <option value="Active">Active</option>
                            <option value="Inactive">Inactive</option>
                        </optgroup>
                    </select>
                    @if ($errors->has('status'))
                        <span class="err">
                            <strong>{{ $errors->first('status') }}.</strong>
                        </span>
                    @endif
                </div>
            </div>
            <div class="form-group row mt-4">
                <label class="col-md-3"></label>
                <div class="col-md-9" style="display: flex; justify-content: flex-end;">
                    <a href="{{ url('document_numbering') }}" class="btn btn-danger">Cancel</a>&nbsp;&nbsp;
                    <button type="submit" class="btn btn-success">Submit</button>
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/Document Numbering/edit.blade.php
@extends('adminlayouts.master')
@section('content')

    <style>
        .err {
            color: red;
        }
    </style>

    <div class="page-header">
        <div class="title">
            <h4 class="text-primary">Edit Document Numbering</h4>
        </div>
    </div>
    <form method="post" action="{{ route('document_numbering.update', $data->id) }}" class="form-horizontal" enctype="multipart/form-data">
        {{ csrf_field() }}

        @if (!empty($data->id) || 1 == 1)
            <input type="hidden" name="_method" value="PATCH">
        @endif

        <input type="hidden" id="id" name="id" value="{{ $data['id'] or '' }}">

        <div class="pd-20 card-box mb-30 ">
            
            <div class="form-group row mt-3">
                <label class="col-sm-2">Name :</label>
                <div class="col-sm-4 col-md-4">
                    <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @enderror"
                        value="{{ $data->name }} " placeholder="Enter Name.">
                    @if ($errors->has('name'))
                        <span class="err">
                            <strong>{{ $errors->first('name') }}.</strong>
                        </span>
                    @endif
                </div>

                <label class="col-sm-2 pt-2">Company Name :</label>
                <div class="col-sm-4 col-md-4">
                    <select class="custom-select2 form-control @error('company') is-invalid @enderror" name="company"
                        id="company" style="width: 100%; height: 38px;">
                        <optgroup label="Organization Company">
                            @foreach($organization as $key => $comps)
                               <option value="{{$key}}" 
                                    @if($key == $data['company'])
                                        Selected
                                    @endif>{{$comps}}
                                </option>
                            @endforeach
                        </optgroup>
                    </select>
                    @if ($errors->has('company'))
                        <span class="err">
                            <strong>{{ $errors->first('company') }}.</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group row mt-3">
                <label class="col-sm-2 pt-2">Document Type :</label>
                <div class="col-sm-4 col-md-4">
                    <select class="custom-select2 form-control @error('document_type') is-invalid @enderror" name="document_type"
                        id="document_type" style="width: 100%; height: 38px;">
                        <option value="{{ $data->document_type }}" selected>{{ $data->document_type }} </option>
                        <optgroup label="Document Type">
                            <option value="File">File</option>
                            <option value="QR-Code">QR-Code</option>
                        </optgroup>
                    </select>
                    @if ($errors->has('document_type'))
                        <span class="err">
                            <strong>{{ $errors->first('document_type') }}.</strong>
                        </span>
                    @endif
                </div>
                
                <label class="col-sm-2 pt-2">Financial Year :<span style="color:red;"> *</span></label>
                <div class="col-sm-4 col-md-4">
                    <select class="custom-select2 form-control @error('financial_year') is-invalid @enderror" name="financial_year"
                        id="financial_year" style="width: 100%; height: 38px;">
                        <optgroup label="Financial Year">
                            @foreach($financial_year as $key => $comps)
                               <option value="{{$key}}" 
                                    @if($key == $data['financial_year'])
                                        Selected
                                    @endif>{{$comps}}
                                </option>
                            @endforeach
                        </optgroup>
                    </select>
                    @if ($errors->has('financial_year'))
                        <span class="err">
                            <strong>{{ $errors->first('financial_year') }}.</strong>
                        </span>
                    @endif
                </div>
            </div>
            
            <div class="form-group row mt-3">
                <label class="col-sm-2">Prefix :</label>
                <div class="col-sm-4 col-md-4">
                    <input type="text" name="prefix" id="prefix"
                        class="form-control  @error('prefix') is-invalid @enderror" value="{{ $data->prefix }}"
                        placeholder="Enter Prefix.">
                    @if ($errors->has('prefix'))
                        <span class="err">
                            <strong>{{ $errors->first('prefix') }}.</strong>
                        </span>
                    @endif
                </div>

                <label class="col-sm-2">Suffix :</label>
                <div class="col-sm-4 col-md-4">
                    <input type="text" name="suffix" id="suffix" class="form-control @error('suffix') is-invalid @enderror""
                        value="{{ $data->End_Doc_No }}" placeholder="Enter Suffix.">
                    @if ($errors->has('suffix'))
                        <span class="err">
                            <strong>{{ $errors->first('suffix') }}.</strong>
                        </span>
                    @endif
                </div>
            </div>
            
            <div class="form-group row mt-3">
                <label class="col-sm-2">Start Doc. No. :</label>
                <div class="col-sm-4 col-md-4">
                    <input type="text" name="Start_Doc_No" id="Start_Doc_No"
                        class="form-control @error('Start_Doc_No') is-invalid @enderror" value="{{ $data->Start_Doc_No }}"
                        placeholder="Enter Starting Document Number.">
                    @if ($errors->has('Start_Doc_No'))
                        <span class="err">
                            <strong>{{ $errors->first('Start_Doc_No') }}.</strong>
                        </span>
                    @endif
                </div>

                <label class="col-sm-2">End Doc. No. :</label>
                <div class="col-sm-4 col-md-4">
                    <input type="text" name="End_Doc_No" id="End_Doc_No" class="form-control @error('End_Doc_No') is-invalid @enderror"
                        value="{{ $data->End_Doc_No }}" placeholder="Enter Ending Document Number.">
                    @if ($errors->has('End_Doc_No'))
                        <span class="err">
                            <strong>{{ $errors->first('End_Doc_No') }}.</strong>
                        </span>
                    @endif
                </div>
            </div>
            
            <div class="form-group row mt-3">
                <label class="col-sm-2 pt-2">Document Numbering Status :</label>
                <div class="col-sm-4 col-md-4">
                    <select class="custom-select2 form-control @error('status') is-invalid @enderror" name="status"
                        id="status" style="width: 100%; height: 38px;">
                        <option value="{{ $data->status }}" selected>{{ $data->status }}</option>
                        <optgroup label="Document Numbering Status">
                            <option value="Active">Active</option>
                            <option value="Inactive">Inactive</option>
                        </optgroup>
                    </select>
                    @if ($errors->has('status'))
                        <span class="err">
                            <strong>{{ $errors->first('status') }}.</strong>
                        </span>
                    @endif
                </div>
            </div>
            <div class="form-group row mt-4">
                <label class="col-md-3"></label>
                <div class="col-md-9" style="display: flex; justify-content: flex-end;">
                    <a href="{{ url('document_numbering') }}" class="btn btn-danger">Cancel</a>&nbsp;&nbsp;
                    <button type="submit" class="btn btn-success">Submit</button>
                </div>
            </div>
        </div>
    </form>

@endsection

resources/views/Document Numbering/grid.blade.php
@extends('adminlayouts.master')
@section('content')
    <div class="pd-ltr-20 xs-pd-20-10">
        <div class="min-height-200px">
            <div class="page-header">
                <div class="row">
                    <!--@if (Session::has('flash_message'))-->
                    <!--    <div class=" col-sm-12">-->
                    <!--        <div class="alert alert-success alert-dismissible">-->
                    <!--            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>-->
                    <!--            <strong>Success!</strong> {{ Session::get('flash_message') }}.-->
                    <!--        </div>-->

                    <!--    </div>-->
                    <!--@endif-->
                    <div class="col-md-6 col-sm-12">
                        <div class="title">
                            <h4>Document Numbering</h4>
                        </div>
                        <nav aria-label="breadcrumb" role="navigation">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a class="text-primary" href="{{ url('index') }}">Home</a></li>
                                <li class="breadcrumb-item "><a >Document Numbering</a></li>
                            </ol>
                        </nav>
                    </div>
                    <div class="col-md-6 col-sm-12 text-right">
                        <a class="btn btn-primary" href="{{ route('document_numbering.create') }}" role="button">
                            <span class="micon ti ti-plus"></span>&nbsp;&nbsp;<span class="mtext">Add</span>
                        </a>

                    </div>
                </div>
            </div>


            <!-- Export Datatable start -->
            <div class="card-box mb-30">
                <div class="pd-20">
                    <h4 class="text-blue h4">Document Numbering List</h4>
                </div>
                <div class="pb-20">
                    <table class="table hover multiple-select-row data-table-export nowrap">
                        <thead>
                            <tr>
                                <th>Sr No.</th>
                                <th>Name</th>
                                <th>Company</th>
                                <th>Doc. Type</th>
                                <th>Financial Year</th>
                                <th>Prefix</th>
                                <th>Suffix</th>
                                <th>Start Doc. No.</th>
                                <th>End Doc. No.</th>
                                <th>Next Doc. No.</th>
                                <th>Status</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($data as $key => $file_type)
                                <tr>
                                    <td>{{ $key + 1 }}</td>
                                    <td>{{ $file_type->name }}</td>
                                    <td><strong>{{ $file_type->company }}</strong></td>
                                    <td>{{ $file_type->document_type }}</td>
                                    <td>{{ $file_type->financial_year }}</td>
                                    <td>{{ $file_type->prefix }}</td>
                                    <td>{{ $file_type->suffix }}</td>
                                    <td>{{ $file_type->Start_Doc_No }}</td>
                                    <td>{{ $file_type->End_Doc_No }}</td>
                                    <td>{{ $file_type->Next_Doc_No }}</td>
                                    @if ($file_type->status == 'Active')
                                        <td>
                                            <span class="badge bg-success tips text-light" data-bs-toggle="popover" title="Active">
                                                Active
                                            </span>
                                        </td>
                                    @else()
                                        <td>
                                            <span class="badge bg-danger tips text-light" data-bs-toggle="popover" title="Inactive">
                                                Inactive
                                            </span>
                                        </td>
                                    @endif
                                    <td>
                                        <a href="{{ route('document_numbering.edit', $file_type->id) }}" class="btn btn-info btn-sm">
                                            <i class="micon dw dw-pencil-1"></i>
                                        </a>
                                    </td>

                                    <td>
                                        <form action="{{ route('document_numbering.destroy', $file_type->id) }}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <input name="_method" type="hidden" value="DELETE">
                                            <button type="submit" class="btn btn-danger btn-sm "
                                                onclick="return confirm('Are you sure to delete?')"><i
                                                    class="micon dw dw-trash"></i>
                                            </button>
                                        </form>

                                    </td>
                                </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
            <!-- Export Datatable End -->
        </div>
        @include('adminlayouts.footer')
    </div>
@endsection

@section('scripts')
    <script type="text/javascript">
        function confirmation() {
            var result = confirm("Are you sure to delete?");
            if (result) {
                // Delete logic goes here
            }
        }
    </script>
@endsection('scripts')