routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\ResetPasswordController;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\financial_yearController;
use App\Http\Controllers\departmentController;
use App\Http\Controllers\statusController;
use App\Http\Controllers\organizationController;
use App\Http\Controllers\document_numberingController;
use App\Http\Controllers\file_masterController;
use App\Http\Controllers\QrCodeController;
use App\Http\Controllers\Department_DetailsController;
use App\Http\Controllers\InwardController;
use App\Http\Controllers\InwardformController;
use App\Http\Controllers\ForwardController;
use App\Http\Controllers\ForwardformController;
use App\Http\Controllers\mis_user_wiseController;
use App\Http\Controllers\Error_PageController;
use App\Http\Controllers\In_TransitController;
use App\Http\Controllers\CloseController;
use App\Http\Controllers\CloseformController;
use App\Http\Controllers\File_TypeController;
use App\Http\Controllers\MISController;
use App\Http\Controllers\file_statusController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

/* -------------------------------Authenticate starting here -------------------------------------- */
// User Register
Route::get('/register', [RegisterController::class, 'register'])->name('register');
Route::post('/register/store', [RegisterController::class, 'store'])->name('register.store');

// User Login
Route::get('/login', [LoginController::class, 'login'])->name('login');
Route::post('/login/store', [LoginController::class, 'authenticate'])->name('login.store');

// Logout
Route::get('/logout', [LoginController::class, 'logout'])->name('dept_logout');

// Forgot Password Password
Route::get('/forget-password', [ForgotPasswordController::class, 'getEmail'])->name('forget-password');
Route::post('/forget-password/store', [ForgotPasswordController::class, 'postEmail'])->name('forget-password.store');

// Password reset routes...
Route::get('/reset-password/{token}', [ResetPasswordController::class, 'getPassword'])->where('token','[0-9a-zA-Z]+')->name('reset-password');
Route::post('/reset-password', [ResetPasswordController::class, 'updatePassword'])->name('reset-password.update');

/* -------------------------------Authenticate ending here ---------------------------------------- */

Route::group(['middleware' => ['auth', 'preventBackHistoryMiddleware']], function() {

    // Dashboard
    Route::get('/index', [HomeController::class, 'index'])->name('admin_dashboard');

    // Upload File Directory
    Route::get('/d', [HomeController::class, 'd'])->name('upload_file_d');

    /* ------------User Online Status ------------ */
    Route::get('/check', [UserController::class, 'userOnlineStatus'])->name('UserOnlineStatus');

    /* ---------------------------------------Setup start here.----------------------------------- */
    Route::resource('/users', RegisterController::class);
    Route::resource('/financial_year', financial_yearController::class);
    Route::resource('/department', departmentController::class);
    Route::resource('/status', statusController::class);
    Route::resource('/organization', organizationController::class);
    Route::resource('/document_numbering', document_numberingController::class);


    /* --------------------------------------- File Master ----------------------------------- */
    Route::resource('/file_master', file_masterController::class);
    Route::get('/file_master_log_history/{id}', [file_masterController::class, 'File_Master_Log_History'])->name('File_Master_Log_History');

    Route::get('/generate-qrcode/{id}', [QrCodeController::class, 'index'])->name('generate-qrcode');
    Route::get('/Department_Details/{id}', [Department_DetailsController::class, 'Department_Details'])->name('Department_Details');

    Route::get('/Inward', [InwardController::class, 'Inward'])->name('Inward');
    Route::get('/Inwardsearch', [InwardController::class, 'search'])->name('Inwardsearch');
    Route::resource('/Inwardform', InwardformController::class);

    Route::get('/Forward', [ForwardController::class, 'Forward'])->name('Forward');
    Route::get('/Forwardsearch', [ForwardController::class, 'forwardsearch'])->name('Forwardsearch');
    Route::resource('/Forwardform', ForwardformController::class);
    Route::post('api/department-user', [ForwardController::class, 'DepartmentUser']);
    Route::post('department-table-no', [ForwardController::class, 'DepartmentUserTableNumber']);

    Route::resource('/in_transit', In_TransitController::class);

    Route::get('/Close', [CloseController::class, 'Close'])->name('Close');
    Route::get('/Closefilesearch', [CloseController::class, 'Closedsearch'])->name('Closefilesearch');
    Route::resource('/close_result', CloseformController::class);

    /* ---------------------------------------Master File start here.----------------------------------- */
    Route::resource('/file_type', File_TypeController::class);

    /* --------------------------------------- Report ----------------------------------- */
    Route::get('/MIS', [MISController::class, 'MIS'])->name('MIS');
    Route::get('/mis_department_user_wise/{id}', [MISController::class, 'mis_department_user_wise'])->name('mis_department_user_wise');
    Route::get('/mis_user_wise', [mis_user_wiseController::class, 'mis_user_wise'])->name('mis_user_wise');
    Route::get('/file_status', [file_statusController::class, 'file_status'])->name('file_status');
    Route::get('/check_file_history', [file_statusController::class, 'check_file_history'])->name('check_file_history');
    Route::post('/check_file_history_search', [file_statusController::class, 'check_file_history_search'])->name('check_file_history_search');

    // ----------------------------- search user management ------------------------------//
    Route::post('search/user/list', [mis_user_wiseController::class, 'searchUser'])->name('search/user/list');

});

/* ---------------------------------------Error Pages start here.---------------------------------- */
Route::get('/400_Error', [Error_PageController::class, '400_Error'])->name('400_Error');
Route::get('/403_Error', [Error_PageController::class, '403_Error'])->name('403_Error');
Route::get('/404_Error', [Error_PageController::class, '404_Error'])->name('404_Error');
Route::get('/500_Error', [Error_PageController::class, '500_Error'])->name('500_Error');
Route::get('/503_Error', [Error_PageController::class, '503_Error'])->name('503_Error');

resources/views/File Master/grid.blade.php
@extends('adminlayouts.master')
@section('content')
    <div class="pd-ltr-20 xs-pd-20-10">
        <div class="min-height-200px">
            <div class="page-header">
                <div class="row">
                    @if (Session::has('file_master_msg'))
                        <div class=" col-sm-12">
                            <div class="alert alert-success alert-dismissible">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                <strong>{{ Session::get('file_master_msg') }}</strong> .
                            </div>

                        </div>
                    @endif
                    <div class="col-md-6 col-sm-12">
                        <div class="title">
                            <h4>File Master</h4>
                        </div>
                        <nav aria-label="breadcrumb" role="navigation">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a class="text-primary" href="{{ url('index') }}">Home</a>
                                </li>
                                <li class="breadcrumb-item "><a>File Master</a></li>
                            </ol>
                        </nav>
                    </div>
                    <div class="col-md-6 col-sm-12 text-right">
                        <a class="btn btn-primary" href="{{ route('file_master.create') }}" role="button">
                            <span class="micon ti ti-plus"></span>&nbsp;&nbsp;<span class="mtext">Add</span>
                        </a>

                    </div>
                </div>
            </div>


            <!-- Export Datatable start -->
            <div class="card-box mb-30">
                <div class="pd-20">
                    <h4 class="text-blue h4">File List</h4>
                </div>
                <div class="pb-20">
                    <table class="table hover multiple-select-row data-table-export nowrap">
                        <thead>
                            <tr>
                                <th>Sr No.</th>
                                <th>File No.</th>
                                <th>Created Date</th>
                                <th>File Type</th>
                                <th>Subject</th>
                                <th>Tipani</th>
                                <th>Docs</th>
                                <th>Status</th>
                                <th>Created by</th>
                                <th>Last Forwarded to</th>
                                <th>Print Documentation</th>
                                <th>File History</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($data6 as $key => $file_type)

                                    <tr>
                                        <td>{{ $key + 1 }}</td>
                                        <td>{{ $file_type->file_master_no }}</td>
                                        <td>{{date('d F, Y',strtotime($file_type->inserted_dt)) }}</td>
                                        <td>{{ $file_type->type }}</td>
                                        <td>{{ $file_type->subject }}</td>
                                        <td>{{ $file_type->total_pages_of_tipani }}</td>
                                        <td>{{ $file_type->total_pages_of_docs }}</td>

                                        @if ($file_type->status == '14')
                                            <td>Closed / निकाली</td>
                                        @elseif($file_type->status == '13')
                                            <td>Accepted</td>
                                        @elseif($file_type->status == '12')
                                            <td>In Transit</td>
                                        @elseif($file_type->status == '10')
                                            <td>Created </td>
                                        @else()
                                            <td>Partially Completed</td>
                                        @endif

                                        <td>{{ $file_type->created_by }}</td>
                                        <td>{{ $file_type->name }}</td>
                                        <td>
                                            <a href="{{ url('generate-qrcode') }}/{{ $file_type->id }}"
                                                class="btn btn-primary btn-sm"><i class="micon dw dw-print"></i></a>
                                        </td>
                                        <td>
                                            <a href="{{ url('file_master_log_history') }}/{{ $file_type->id }}"
                                                class="btn btn-success btn-sm"><i class="micon dw dw-file"></i></a>
                                        </td>
                                        <td>
                                            <a href="{{ route('file_master.edit', $file_type->id) }}"
                                                class="btn btn-info btn-sm">
                                                <i class="micon dw dw-pencil-1"></i>
                                            </a>
                                        </td>

                                        <td>
                                            <form action="{{ route('file_master.destroy', $file_type->id) }}"
                                                method="post">
                                                @csrf
                                                @method('DELETE')
                                                <input name="_method" type="hidden" value="DELETE">
                                                <button type="submit" class="btn btn-danger btn-sm "
                                                    onclick="return confirm('Are you sure to delete?')"><i
                                                        class="micon dw dw-trash"></i>
                                                </button>
                                            </form>

                                        </td>
                                    </tr>

                            @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
            <!-- Export Datatable End -->
        </div>
        @include('adminlayouts.footer')
    </div>
@endsection

@section('scripts')
    <script type="text/javascript">
        function confirmation() {
            var result = confirm("Are you sure to delete?");
            if (result) {
                // Delete logic goes here
            }
        }
    </script>
@endsection('scripts')

resources/views/File Master/log_history.blade.php
@extends('adminlayouts.master')
@section('content')

    <style>
        .err {
            color: red;
        }

    </style>
    
    <div class="page-header">
        <div class="title">
            <h4 class="text-primary">All Transaction History</h4>
            @if (!empty($data->id) || 1 == 1)
                <span class="ml-10">File No.: <b>{{ $data->file_master_no  }}</b></span>
            @endif
        </div>
    </div>
    
    <!-- Export Datatable start -->
    <div class="card-box mb-30">
        <div class="pd-20">
            <h4 class="text-blue h4">All Transaction History </h4>
        </div>
        <div class="pb-20">
            <table class="table hover table-bordered table-responsive  nowrap p-3">
                <thead class="text-light" style="background:#0285D0;">
                    <tr>
                        <th rowspan="2">Date</th>
                        <th rowspan="2">Status</th>
                        <th colspan="3" class="text-center">From</th>
                        <th colspan="3" class="text-center">To</th>
                        <th rowspan="2">Method</th>
                        <th rowspan="2">No. of Tipani Pages</th>
                        <th rowspan="2">Tipani File</th>
                        <th rowspan="2">Remark / Tipani</th>
                    </tr>
                    <tr>
                        <th>Employee</th>
                        <th>Department</th>
                        <th>Table</th>
                        <th>Employee</th>
                        <th>Department</th>
                        <th>Table</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($dataclosed as $dataclose)
                    <tr>
                        <!--Last row Created record -->
                        <td>{{ $dataclose->inserted_dt }}</td>
                        <td>Closed / निकाली</td>
                        <td>{{ $dataclose->user_login }}</td>
                        <td>{{ $dataclose->name }}</td>
                        <td>{{ $dataclose->tableno_login }}</td>
                        <td>{{ $dataclose->user_login }}</td>
                        <td>{{ $dataclose->name }}</td>
                        <td>{{ $dataclose->tableno_login }}</td>
                        <td>By Hand </td>
                        <td>{{ $dataclose->tipani_page  }}</td>
                        @if (!empty($dataclose->pdf))
                           <td>
                               <a href="{{ $path.$dataclose->pdf }}" target="_blank" class="btn btn-danger btn-sm ml-3">
                                   <i class="micon fa fa-file-pdf-o"></i>
                               </a>
                            </td>
                        @else
                           <td width="10%">NULL</td>
                        @endif
                        
                        <td>{{ $dataclose->remark }}</td>
                    </tr>
                    @endforeach
                    @foreach($all_data_trx as $datafwd)
                        <tr>
                            <td >{{ $datafwd->inserted_dt }}</td>
                            @if ($datafwd->file_status == '14')
                                <td>Closed / निकाली</td>
                            @elseif($datafwd->file_status == '13')
                                <td>Accepted</td>
                            @elseif($datafwd->file_status == '12')
                                <td>In Transit</td>
                            @elseif($datafwd->file_status == '10')
                                <td>Created </td>
                            @else()
                                <td>Partially Completed</td>
                            @endif

                            <td>{{ $datafwd->from_emp  }}</td>
                            <td>{{ $datafwd->from_departmentname  }}</td>
                            <td>{{ $datafwd->from_tableno  }}</td>

                            <td>{{ $datafwd->for_usersname }}</td>
                            <td>{{ $datafwd->for_departmentname  }}</td>
                            <td> {{ $datafwd->for_tableno  }} </td>

                            <td>{{ $datafwd->method }}/ {{ $datafwd->user_details }}</td>
                            <td>{{ $datafwd->tipani_page  }}</td>
                            @if (!empty($datafwd->tipani_file))
                               <td>
                                    <a href="{{ $path.$datafwd->tipani_file }}" target="_blank" class="btn btn-danger btn-sm ml-3">
                                       <i class="micon fa fa-file-pdf-o"></i>
                                    </a>
                                </td>
                            @else
                               <td width="10%">NULL</td>
                            @endif
                            
                            <td>{{ $datafwd->remark }}</td>
                        </tr>
                    @endforeach

                    @foreach($datacreated as $data1)
                    <tr>
                     <!--Last row Created record -->
                        <td>{{ $data1->inserted_dt }}</td>
                        <td>Created</td>
                        <td>{{ $data1->created_by }}</td>
                        <td>{{ $data1->name }}</td>
                        <td>{{ $data1->table_no }}</td>

                        <td>{{ $data1->created_by }}</td>
                        <td>{{ $data1->name }}</td>
                        <td>{{ $data1->table_no }}</td>

                        <td>By Hand </td>
                        <td>{{ $data1->total_pages_of_tipani  }}</td> 
                        @if (!empty($data1->pdf))
                            <td>
                               <a href="{{ url('/') }}/myfinalimg/{{ $data1->pdf }}" target="_blank" class="btn btn-danger btn-sm ml-3">
                                   <i class="micon fa fa-file-pdf-o"></i>
                               </a>
                            </td>
                        @else
                           <td width="10%">NULL</td>
                        @endif
                        
                        <!--<td>{{ $data1->pdf }}</td>-->
                        <td>{{ $data1->file_detail }}</td>
                    </tr>
                    @endforeach
                </tbody>

            </table>
        </div>
    </div>
    <!-- Export Datatable End -->
@endsection